session: ${name}
root: ${root}

windows:
  - name: " "
    commands:
      - nvim "+Telescope find_files"
  - name: " "
    panes:
      - type: horizontal
        commands:
          - clear
          - clear
